import type { BlankInventoryItem } from "@/types";

// Mock MVP inventory only. Quantities are static seed values, not live stock.
export const mockBlankInventory = [
  {
    id: "blank-echo-park-laa-1801",
    providerId: "provider-echo-park-print-works",
    blankBrand: "Los Angeles Apparel",
    styleName: "1801GD Garment Dye Tee",
    garmentType: "t_shirt",
    colors: ["black", "white", "cement", "forest"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    stockStatus: "in_stock",
    quantityOnHand: 420,
    isPremiumBlank: true,
  },
  {
    id: "blank-echo-park-ascolour-5001",
    providerId: "provider-echo-park-print-works",
    blankBrand: "AS Colour",
    styleName: "Staple Tee",
    garmentType: "t_shirt",
    colors: ["black", "white", "bone"],
    sizes: ["S", "M", "L", "XL"],
    stockStatus: "limited",
    quantityOnHand: 96,
    isPremiumBlank: true,
  },
  {
    id: "blank-harbor-independent-ind4000",
    providerId: "provider-harbor-stitch-print",
    blankBrand: "Independent Trading Co.",
    styleName: "IND4000 Heavyweight Hoodie",
    garmentType: "hoodie",
    colors: ["black", "charcoal", "alpine green"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    stockStatus: "in_stock",
    quantityOnHand: 260,
    isPremiumBlank: true,
  },
  {
    id: "blank-harbor-bellacanvas-3001",
    providerId: "provider-harbor-stitch-print",
    blankBrand: "Bella+Canvas",
    styleName: "3001 Unisex Jersey Tee",
    garmentType: "t_shirt",
    colors: ["black", "white", "athletic heather"],
    sizes: ["XS", "S", "M", "L", "XL", "2XL"],
    stockStatus: "in_stock",
    quantityOnHand: 610,
    isPremiumBlank: false,
  },
  {
    id: "blank-civic-center-everybody-trash-tee",
    providerId: "provider-civic-center-ink",
    blankBrand: "Everybody.World",
    styleName: "Trash Tee",
    garmentType: "t_shirt",
    colors: ["black", "white", "natural"],
    sizes: ["S", "M", "L", "XL"],
    stockStatus: "limited",
    quantityOnHand: 72,
    isPremiumBlank: true,
  },
  {
    id: "blank-civic-center-econscious-tote",
    providerId: "provider-civic-center-ink",
    blankBrand: "econscious",
    styleName: "Organic Cotton Tote",
    garmentType: "tote",
    colors: ["natural", "black"],
    sizes: ["OS"],
    stockStatus: "in_stock",
    quantityOnHand: 340,
    isPremiumBlank: true,
  },
  {
    id: "blank-barrio-logan-gildan-5000",
    providerId: "provider-barrio-logan-press",
    blankBrand: "Gildan",
    styleName: "5000 Heavy Cotton Tee",
    garmentType: "t_shirt",
    colors: ["black", "white", "sand"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    stockStatus: "in_stock",
    quantityOnHand: 500,
    isPremiumBlank: false,
  },
  {
    id: "blank-inland-laa-1807",
    providerId: "provider-inland-blank-lab",
    blankBrand: "Los Angeles Apparel",
    styleName: "1807GD Long Sleeve",
    garmentType: "long_sleeve",
    colors: ["black", "white", "smoke"],
    sizes: ["S", "M", "L", "XL"],
    stockStatus: "in_stock",
    quantityOnHand: 380,
    isPremiumBlank: true,
  },
  {
    id: "blank-inland-independent-prm3500",
    providerId: "provider-inland-blank-lab",
    blankBrand: "Independent Trading Co.",
    styleName: "PRM3500 Midweight Crewneck",
    garmentType: "crewneck",
    colors: ["black", "bone", "charcoal"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    stockStatus: "limited",
    quantityOnHand: 84,
    isPremiumBlank: true,
  },
] satisfies BlankInventoryItem[];
