import type { ProviderCapability, ProviderProfile } from "@/types";

// Mock MVP seed data only. These fictional Southern California providers are
// shaped for the future deterministic routing engine.
export const mockProviders = [
  {
    id: "provider-echo-park-print-works",
    profileId: "profile-provider-echo-park",
    businessName: "Echo Park Print Works",
    legalBusinessName: "Echo Park Print Works LLC",
    dbaName: "Echo Park Print Works",
    contactName: "Nina Alvarez",
    businessEmail: "ops@echoparkprintworks.example",
    phone: "(213) 555-0132",
    streetAddress: "1824 Sunset Blvd",
    city: "Los Angeles",
    state: "CA",
    zip: "90026",
    sellersPermitNumber: "CA-SP-482913",
    einPlaceholder: "12-3456789",
    businessType: "LLC",
    yearsInOperation: 6,
    supplierAccountReadiness: [
      "S&S Activewear",
      "alphabroder",
      "Los Angeles Apparel wholesale",
    ],
    preferredBlankDistributors: [
      "Los Angeles Apparel wholesale",
      "AS Colour",
      "S&S Activewear",
    ],
    blankSourcingNotes:
      "Keeps core Los Angeles Apparel and AS Colour styles on hand and can source specialty colors with notice.",
    fulfillmentCutoffTime: "2:00 PM PT",
    reorderLeadTimeDays: 4,
    serviceRadiusMiles: 35,
    supportsLocalPickup: true,
    tier: "preferred",
    verificationStatus: "verified",
    turnaroundSlaDays: 3,
    dailyCapacityUnits: 180,
    currentCapacityUsed: 92,
    specialties: ["DTG on premium tees", "small brand drops", "soft-hand prints"],
  },
  {
    id: "provider-harbor-stitch-print",
    profileId: "profile-provider-long-beach",
    businessName: "Harbor Stitch & Print",
    legalBusinessName: "Harbor Stitch and Print Inc.",
    dbaName: "Harbor Stitch & Print",
    contactName: "Marcus Bell",
    businessEmail: "hello@harborstitchprint.example",
    phone: "(562) 555-0148",
    streetAddress: "411 Pine Ave",
    city: "Long Beach",
    state: "CA",
    zip: "90802",
    sellersPermitNumber: "CA-SP-517224",
    einPlaceholder: "23-4567890",
    businessType: "Corporation",
    yearsInOperation: 9,
    supplierAccountReadiness: ["S&S Activewear", "SanMar", "Bella+Canvas"],
    preferredBlankDistributors: [
      "S&S Activewear",
      "SanMar",
      "Bella+Canvas",
    ],
    blankSourcingNotes:
      "Strong fleece and core tee sourcing through national distributors with same-week replenishment.",
    fulfillmentCutoffTime: "1:00 PM PT",
    reorderLeadTimeDays: 5,
    serviceRadiusMiles: 45,
    supportsLocalPickup: true,
    tier: "verified",
    verificationStatus: "verified",
    turnaroundSlaDays: 4,
    dailyCapacityUnits: 220,
    currentCapacityUsed: 130,
    specialties: ["DTG and embroidery", "event merch", "fleece basics"],
  },
  {
    id: "provider-civic-center-ink",
    profileId: "profile-provider-santa-ana",
    businessName: "Civic Center Ink",
    legalBusinessName: "Civic Center Ink Studio LLC",
    dbaName: "Civic Center Ink",
    contactName: "Elena Park",
    businessEmail: "jobs@civiccenterink.example",
    phone: "(714) 555-0121",
    streetAddress: "725 W Civic Center Dr",
    city: "Santa Ana",
    state: "CA",
    zip: "92701",
    sellersPermitNumber: "CA-SP-551903",
    einPlaceholder: "34-5678901",
    businessType: "LLC",
    yearsInOperation: 4,
    supplierAccountReadiness: ["Everybody.World", "econscious", "S&S Activewear"],
    preferredBlankDistributors: [
      "Everybody.World",
      "econscious",
      "S&S Activewear",
    ],
    blankSourcingNotes:
      "Leans on premium blanks for rush retail-ready jobs and keeps tote inventory deeper than fleece inventory.",
    fulfillmentCutoffTime: "12:00 PM PT",
    reorderLeadTimeDays: 3,
    serviceRadiusMiles: 40,
    supportsLocalPickup: false,
    tier: "verified",
    verificationStatus: "verified",
    turnaroundSlaDays: 2,
    dailyCapacityUnits: 140,
    currentCapacityUsed: 78,
    specialties: ["rush DTG", "tour test runs", "retail-ready packing"],
  },
  {
    id: "provider-barrio-logan-press",
    profileId: "profile-provider-san-diego",
    businessName: "Barrio Logan Press",
    legalBusinessName: "Barrio Logan Press Cooperative",
    dbaName: "Barrio Logan Press",
    contactName: "Sofia Martinez",
    businessEmail: "studio@barriologanpress.example",
    phone: "(619) 555-0180",
    streetAddress: "2214 Main St",
    city: "San Diego",
    state: "CA",
    zip: "92113",
    sellersPermitNumber: "CA-SP-603114",
    einPlaceholder: "45-6789012",
    businessType: "Cooperative",
    yearsInOperation: 3,
    supplierAccountReadiness: ["S&S Activewear pending", "Local blank brokers"],
    preferredBlankDistributors: [
      "Local blank brokers",
      "S&S Activewear pending",
    ],
    blankSourcingNotes:
      "Can source budget-friendly blanks quickly but is still building premium wholesale depth.",
    fulfillmentCutoffTime: "11:00 AM PT",
    reorderLeadTimeDays: 6,
    serviceRadiusMiles: 55,
    supportsLocalPickup: true,
    tier: "emerging",
    verificationStatus: "pending",
    turnaroundSlaDays: 5,
    dailyCapacityUnits: 120,
    currentCapacityUsed: 48,
    specialties: ["artist merch", "DTF transfers", "community pickup"],
  },
  {
    id: "provider-inland-blank-lab",
    profileId: "profile-provider-riverside",
    businessName: "Inland Blank Lab",
    legalBusinessName: "Inland Blank Lab LLC",
    dbaName: "Inland Blank Lab",
    contactName: "Drew Kim",
    businessEmail: "production@inlandblanklab.example",
    phone: "(951) 555-0157",
    streetAddress: "3850 Market St",
    city: "Riverside",
    state: "CA",
    zip: "92501",
    sellersPermitNumber: "CA-SP-645208",
    einPlaceholder: "56-7890123",
    businessType: "LLC",
    yearsInOperation: 5,
    supplierAccountReadiness: [
      "S&S Activewear",
      "alphabroder",
      "Independent Trading Co.",
    ],
    preferredBlankDistributors: [
      "Independent Trading Co.",
      "alphabroder",
      "S&S Activewear",
    ],
    blankSourcingNotes:
      "Best set up for replenishment orders and bulk blank sourcing across tees, long sleeves, and fleece.",
    fulfillmentCutoffTime: "3:00 PM PT",
    reorderLeadTimeDays: 5,
    serviceRadiusMiles: 50,
    supportsLocalPickup: false,
    tier: "emerging",
    verificationStatus: "pending",
    turnaroundSlaDays: 4,
    dailyCapacityUnits: 260,
    currentCapacityUsed: 104,
    specialties: ["blank sourcing", "DTG basics", "larger batch capacity"],
  },
] satisfies ProviderProfile[];

export const mockProviderCapabilities = [
  {
    id: "capability-echo-park",
    providerId: "provider-echo-park-print-works",
    printMethods: ["dtg", "dtf"],
    garmentTypes: ["t_shirt", "long_sleeve", "hoodie", "crewneck", "tote"],
    maxOrderQuantity: 300,
    acceptsPremiumBlanks: true,
    notes: "Best fit for DTG-first premium tee and fleece drops under 300 units.",
  },
  {
    id: "capability-harbor",
    providerId: "provider-harbor-stitch-print",
    printMethods: ["dtg", "embroidery", "heat_transfer"],
    garmentTypes: ["t_shirt", "hoodie", "crewneck", "tank"],
    maxOrderQuantity: 400,
    acceptsPremiumBlanks: true,
    notes: "Can handle mixed DTG and embroidery requests for small brands.",
  },
  {
    id: "capability-civic-center",
    providerId: "provider-civic-center-ink",
    printMethods: ["dtg", "dtf"],
    garmentTypes: ["t_shirt", "long_sleeve", "tank", "tote"],
    maxOrderQuantity: 180,
    acceptsPremiumBlanks: true,
    notes: "Strong rush option for DTG tees and totes in Orange County.",
  },
  {
    id: "capability-barrio-logan",
    providerId: "provider-barrio-logan-press",
    printMethods: ["dtg", "dtf", "screen_print"],
    garmentTypes: ["t_shirt", "hoodie", "crewneck", "tote"],
    maxOrderQuantity: 220,
    acceptsPremiumBlanks: false,
    notes: "Pending verification; useful later for San Diego routing scenarios.",
  },
  {
    id: "capability-inland",
    providerId: "provider-inland-blank-lab",
    printMethods: ["dtg", "heat_transfer"],
    garmentTypes: ["t_shirt", "long_sleeve", "hoodie", "crewneck"],
    maxOrderQuantity: 500,
    acceptsPremiumBlanks: true,
    notes: "Higher capacity Inland Empire shop with strong blank sourcing.",
  },
] satisfies ProviderCapability[];
