import type { ProviderCapability, ProviderProfile } from "@/types";

// Mock MVP seed data only. These fictional Southern California providers are
// shaped for the future deterministic routing engine.
export const mockProviders = [
  {
    id: "provider-echo-park-print-works",
    profileId: "profile-provider-echo-park",
    businessName: "Echo Park Print Works",
    contactName: "Nina Alvarez",
    city: "Los Angeles",
    state: "CA",
    zip: "90026",
    serviceRadiusMiles: 35,
    supportsLocalPickup: true,
    tier: "preferred",
    verificationStatus: "verified",
    turnaroundSlaDays: 3,
    dailyCapacityUnits: 180,
    currentCapacityUsed: 92,
    specialties: ["DTG on premium tees", "small brand drops", "soft-hand prints"],
  },
  {
    id: "provider-harbor-stitch-print",
    profileId: "profile-provider-long-beach",
    businessName: "Harbor Stitch & Print",
    contactName: "Marcus Bell",
    city: "Long Beach",
    state: "CA",
    zip: "90802",
    serviceRadiusMiles: 45,
    supportsLocalPickup: true,
    tier: "verified",
    verificationStatus: "verified",
    turnaroundSlaDays: 4,
    dailyCapacityUnits: 220,
    currentCapacityUsed: 130,
    specialties: ["DTG and embroidery", "event merch", "fleece basics"],
  },
  {
    id: "provider-civic-center-ink",
    profileId: "profile-provider-santa-ana",
    businessName: "Civic Center Ink",
    contactName: "Elena Park",
    city: "Santa Ana",
    state: "CA",
    zip: "92701",
    serviceRadiusMiles: 40,
    supportsLocalPickup: false,
    tier: "verified",
    verificationStatus: "verified",
    turnaroundSlaDays: 2,
    dailyCapacityUnits: 140,
    currentCapacityUsed: 78,
    specialties: ["rush DTG", "tour test runs", "retail-ready packing"],
  },
  {
    id: "provider-barrio-logan-press",
    profileId: "profile-provider-san-diego",
    businessName: "Barrio Logan Press",
    contactName: "Sofia Martinez",
    city: "San Diego",
    state: "CA",
    zip: "92113",
    serviceRadiusMiles: 55,
    supportsLocalPickup: true,
    tier: "emerging",
    verificationStatus: "pending",
    turnaroundSlaDays: 5,
    dailyCapacityUnits: 120,
    currentCapacityUsed: 48,
    specialties: ["artist merch", "DTF transfers", "community pickup"],
  },
  {
    id: "provider-inland-blank-lab",
    profileId: "profile-provider-riverside",
    businessName: "Inland Blank Lab",
    contactName: "Drew Kim",
    city: "Riverside",
    state: "CA",
    zip: "92501",
    serviceRadiusMiles: 50,
    supportsLocalPickup: false,
    tier: "emerging",
    verificationStatus: "pending",
    turnaroundSlaDays: 4,
    dailyCapacityUnits: 260,
    currentCapacityUsed: 104,
    specialties: ["blank sourcing", "DTG basics", "larger batch capacity"],
  },
] satisfies ProviderProfile[];

export const mockProviderCapabilities = [
  {
    id: "capability-echo-park",
    providerId: "provider-echo-park-print-works",
    printMethods: ["dtg", "dtf"],
    garmentTypes: ["t_shirt", "long_sleeve", "hoodie", "crewneck", "tote"],
    maxOrderQuantity: 300,
    acceptsPremiumBlanks: true,
    notes: "Best fit for DTG-first premium tee and fleece drops under 300 units.",
  },
  {
    id: "capability-harbor",
    providerId: "provider-harbor-stitch-print",
    printMethods: ["dtg", "embroidery", "heat_transfer"],
    garmentTypes: ["t_shirt", "hoodie", "crewneck", "tank"],
    maxOrderQuantity: 400,
    acceptsPremiumBlanks: true,
    notes: "Can handle mixed DTG and embroidery requests for small brands.",
  },
  {
    id: "capability-civic-center",
    providerId: "provider-civic-center-ink",
    printMethods: ["dtg", "dtf"],
    garmentTypes: ["t_shirt", "long_sleeve", "tank", "tote"],
    maxOrderQuantity: 180,
    acceptsPremiumBlanks: true,
    notes: "Strong rush option for DTG tees and totes in Orange County.",
  },
  {
    id: "capability-barrio-logan",
    providerId: "provider-barrio-logan-press",
    printMethods: ["dtg", "dtf", "screen_print"],
    garmentTypes: ["t_shirt", "hoodie", "crewneck", "tote"],
    maxOrderQuantity: 220,
    acceptsPremiumBlanks: false,
    notes: "Pending verification; useful later for San Diego routing scenarios.",
  },
  {
    id: "capability-inland",
    providerId: "provider-inland-blank-lab",
    printMethods: ["dtg", "heat_transfer"],
    garmentTypes: ["t_shirt", "long_sleeve", "hoodie", "crewneck"],
    maxOrderQuantity: 500,
    acceptsPremiumBlanks: true,
    notes: "Higher capacity Inland Empire shop with strong blank sourcing.",
  },
] satisfies ProviderCapability[];
